<div class="side-block">
	<div class="block-title"><span style="padding-left:10px;">Hỗ trợ trực tuyến</span></div>
    <div class="block-content" style="padding-top:15px;">
    	<table cellpadding="0" cellspacing="0" width="100%" border="0">
        	<tr>
            	<td><img src="<?php echo $this->getSkinUrl('images/support.jpg') ?>" alt="" /></td>
                <td align="center">
                <div style="padding-bottom:10px;"><img src="<?php echo $this->getSkinUrl('images/9.png') ?>" alt="" /></div>
                <div><img src="<?php echo $this->getSkinUrl('images/vietnamvisa.png') ?>" alt="" /></div>
                </td>
            </tr>
            <tr>
            	<td colspan="2">
                	<div class="r">
                    	<div class="a left">Phone:</div>
                        <div class="left">(+84 4) 3 782 2600</div>
                    </div>
                    <div class="r">
                    	<div class="a left">Hotline:</div>
                        <div class="left">(+84 4) 917 2 91769</div>
                    </div>
                    <div class="r">
                    	<div class="a left">E-mail:</div>
                        <div class="left">support@sale.vn</div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <img src="<?php echo $this->getSkinUrl('images/bottom-curve.png') ?>" alt=""/>
</div>
<!--
<script type="text/javascript">
    //var eff = jQuery.noConflict();
    $j(function(){
        $j('#loopedslider').loopedSlider({
            autoHeight: false,
            containerClick: false,
            autoStart:4000,
            restart: 4000,
            slidespeed: 500
        });
    });
</script>
-->
<?php
/* Condition for displaying the sidedeal in the main deal page */
//$cid = Mage::app()->getRequest()->getParam('cid');
$id = Mage::app()->getRequest()->getParam('id');
$catId = 7; // put your category ID in here
$title = $this->__('Todays Side Deal');
if (isset($id)) {
    $catId = 6;
    
}

$cities = array();
$desc = '';
$baseUrl = Mage::getBaseUrl();
$dealsCity = Mage::getSingleton('core/session')->getCity();

//getting the current city
$Totalcities = Mage::getSingleton('core/session')->getTotalCities();

$dealsCityName = $Totalcities[$dealsCity];
$products = Mage::getModel('deal/deal')->getDealCollectionsRadom($dealsCity);


   // $products = Mage::getModel('deal/deal')->getDealCollections($dealsCity);
	
    $currentTime = Mage_Core_Model_Locale::date(null, null, "vi_VN", true);
?>
<div class="side-block">
<img src="<?php echo $this->getSkinUrl('images/top-curve.png') ?>" style="vertical-align:bottom;"/>
<?php
    foreach ($products as $_product) {
        $productId = $_product->getId();

        if ($productId != $id) {
            $model = Mage::getModel('catalog/product'); //getting product model
            $_product = $model->load($_product->getId());
            $city = $_product->getAttributeText('cities');
            $ProductToDate = $_product->getResource()->formatDate($_product->getspecial_to_date(), false);
            $ToDate = strtotime($ProductToDate);
            $ProductFromDate = $_product->getResource()->formatDate($_product->getspecial_from_date(), false);
            $Fromtime = strtotime($ProductFromDate);
            if ($Fromtime < strtotime($currentTime)) {
                //if($city == $dealsCityName ) {
                if (strtotime(date("Y-m-d", $ToDate) . ' ' . $_product->getTime()) >= strtotime($currentTime)) {
                    $productId = $_product->getId();
                    $images = $this->helper('catalog/image')->init($_product, 'image');
                    $desc = $_product->getName();
                    $URL = Mage::getModel('deal/deal')->getProductUrl($productId);
					$sp_price = floor($_product->getSpecialPrice());
					 if (!$_product->isGrouped()) {
                            $discount_price = $_product->getPrice() - $_product->getSpecialPrice();
                            $discount = ($discount_price * 100) / $_product->getPrice();
                            $discount = round($discount);
					 }
                    
?>
  						<div class="block-content" style="padding-top:0px;padding-bottom:10px;">
                        <a href="<?php echo $URL; ?>" style="text-decoration:none;">
                            <div class="midpix">
                           
                            	<div class="sidebar_discount">
                            		<h3 style="text-align:center;padding-top:6px;"><?php echo $this->__('Giảm'); ?></h3>
                            		<span><?php echo $discount . '%'; ?></span>
                                </div>
                                <div class="deal_content_top"><div style="padding-left:10px;"><?php echo substr($desc,0,40); ?></div></div>
                                	<img src="<?php echo $images; ?>" width="233" height="153" alt="" class="border-radium"/>
                                
                                <div class="deal_content border-bottom-radius"><?php echo  Mage::helper('core')->currency($sp_price, true, true) ?></div>
                               
                            
							</div>
                            </a>
                        </div>
                        
                           
<?php
                   
                }
            }
        }
    }
?>
 <img src="<?php echo $this->getSkinUrl('images/bottom-curve.png') ?>" alt=""/>
 </div>


<?php 
$sharelinks = Gclone_Deal_Block_Deal::getsharelinks();
                $facebookfans = $sharelinks['facebookfans'];
if (!empty($facebookfans)) {
 ?>
 		<div class="side-block">
        	<img src="<?php echo $this->getSkinUrl('images/top-curve.png') ?>" style="vertical-align:bottom;"/>
	        <div class="block-content" style="padding-top:0px;padding-bottom:0px;">
                     <iframe src="http://www.facebook.com/plugins/likebox.php?id=<?php echo $facebookfans; ?>&amp;width=243&amp;connections=12&amp;border_color=%23ffffff&amp;stream=false&amp;header=false&amp;height=350" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:243px; height:350px; background: #FFF;" allowTransparency="true">
                    </iframe>
                   </div>
                    <img src="<?php echo $this->getSkinUrl('images/bottom-curve.png') ?>" alt=""/>
         </div>
<?php } ?>