<style>
.col-main .contpad {padding-top:0px;}
</style>
<div class="cart">
	<div class="title-cart" style="padding-bottom:0px;">
    	<h1 style="line-height:41px;padding-left:45px;"><?php echo $this->__('Shopping Cart') ?></h1><br />
        <!--div class="boxStep">
            <div class="step stepActive">Giỏ hàng</div>
            <div class="step stepNone">Buoc 2</div>
            <div class="step stepNone">Buoc 3</div>
            <div class="step stepNone">Buoc 4</div>
        </div-->
    </div>
    
    <div class="page-title title-buttons">
        
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
                <?php //echo $this->getChildHtml('top_methods') ?>
        </ul>
        <?php endif; ?>
    </div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>

    <div style=" margin: 0 auto;">
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" >
    	 <col width="1" />
            <col width="1" />
            <col />
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
            <col width="1" />
            <?php endif ?>
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <?php endif; ?>
            <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <?php endif; ?>

        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    	<table cellpadding="0" cellspacing="0" border="1" width="100%" id="shopping-cart-table " class="data-table cart-table">
        <tbody>
        	<tr style="background:#57891c">
            	<td style="width:8.65%;"><?php echo $this->__('Remove') ?></td>
                <td style="width:45%;"><span class="nobr"><?php echo $this->__('Product Name') ?></span></td>
                 <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                	<td rowspan="<?php echo $mergedCells; ?>"  class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></td>
                <?php endif ?>
                <td class="clscartprice"  style="width:13%;text-align:center;"><span class="nobr"><?php echo $this->__('Price') ?></span></td>
                <td   class="clscartquantity"   style="width:15%;text-align:center;"><?php echo $this->__('Qty') ?></td>
                <td   class="clscarttotal"  style="width:15%;text-align:center;"><?php echo $this->__('Total') ?></td>                           
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                    <?php endif; ?>
        	
            
            	  <?php foreach($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
            </tbody>
            <tfoot>
            	<tr>
                	<td colspan="5">
                    	<p style="float:right;"><span class="sub"><?php echo $this->__('Grand Total:')?></span><span class="subvalue"><?php
//$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
echo Mage::helper('core')->currency(Mage::getSingleton('checkout/session')->getQuote()->getGrandTotal(),true,false); ?></span></p>
                           
                    </td>
                </tr>
            </tfoot>
        </table>
     	<script type="text/javascript">decorateTable('shopping-cart-table')</script>
    
    </form>
    <!--
        <div class="grandtotal">
    <?php
    $sessionorder = Mage::getSingleton('core/session');
    //echo $this->getChildHtml('totals');
    ?>
<!--    <div  class="proceedbtns"><a href="<?php echo $this->getUrl('checkout') ?>"><img src="<?php echo $this->getSkinUrl('images/proceedbtn.jpg') ?>"/></a></div><div class="clear"></div>-->
    <div  class="proceedbtns">
               <button type="button" class="btnnew" value="" onclick="window.location='<?php echo $this->getUrl('checkout') ?>'"><span><?php echo $this->__('Tiếp tục'); ?></span></button>
    </div>
             </div>
    <div class="clear"></div>

    <br/>
    <br/>
    <div class="clearfix" id="gift-form" style="display:none;" >
        <div class="modal_top"></div><a id="closeLink" href="javascript:void(0);">  <img height="39" width="39" src="<?php echo $this->getSkinUrl('images/close.gif') ?>" id="close" class="modal_close" alt=""/></a>
        <form id="giftoption" action="<?php echo $this->getUrl('checkout/cart/giftPost') ?>" method="post" class=''>

            <div class="modal_content">
                <div class="modal_header">
                    <h1><?php echo $this->__('Buy Options'); ?></h1>
                    <p>
                        <small><?php echo $this->__('Fill out the form below and give the gift!'); ?></small>
                    </p>
                </div>


                <ul style="width: 240px; float: left; margin-right: 20px;padding-left:10px;" class="contactul" id="dealmeonegift" >
                    <li>
                        <div  class=""><label for="name" class="contact-label"><?php echo $this->__('Friend Name'); ?> :</label></div>
                        <input  id="order_gift_to_name" maxlength="26" name="order_gift_to_name"   class="input-text required-entry clstxtbox" type="text" value="<?php echo $sessionorder->getorderto(); ?>" />

                    </li>
                    <li >

                        <div class=""><label for="emil" class="contact-label"><?php echo $this->__('Your Name'); ?> :</label></div>
                        <input id="order_gift_from_name" maxlength="40" name="order_gift_from_name"  title="From" class="input-text required-entry clstxtbox" type="text" value="<?php echo $sessionorder->getorderfrom(); ?>" />

                    </li>


                    <li>

                        <div class=""><label for='order_delivery_method_email' class="contact-label"><?php echo $this->__('Friend Email Address'); ?> :</label></div>
                        <input  id="order_gift_recipient_email" name="order_gift_recipient_email"  title="Email" class="input-text required-entry validate-email clstxtbox" type="text"  value="<?php echo $sessionorder->getorderemail(); ?>" />


                    </li>

                </ul>
                <ul style="width: 260px; float: right;" >
                    <li>


                        <div class=""><label for="comment"  class="txtmsg"><?php echo $this->__('Message'); ?> :</label></div>
                        <textarea rows="8" cols="5"id="order_gift_message" name="order_gift_message" title="Message"  class="txtarea"><?php echo $sessionorder->getordermessage(); ?></textarea>

                    </li>
                </ul>
<!--                <div><button type="submit" class="clssubmit" ></button></div>-->
                <div><button type="submit" class="btnnew clssubmit" ><span><?php echo $this->__('Submit'); ?></span></button></div>

            </div>


        </form>
        <div class="modal_bottom"></div>
    </div>
    <div class="clearfix" id="gift-deleteform" style="display:none;" >
        <div class="modal_top"></div>
        <a id="closeLinkDelete" href="javascript:void(0);">  <img height="39" width="39" src="<?php echo $this->getSkinUrl('images/x-close-large.png') ?>" id="close" class="modal_close" alt=""/></a>
        <form action="<?php echo $this->getUrl('checkout/cart/giftDelete') ?>" method="post" class=''>
            <div class="modal_content">
                <div class="modal_header">
                    <h1><?php echo $this->__('Are you sure to delete'); ?></h1>
                </div>
                <div align="center"><button type="submit" class="clssubmit" ></button></div>
            </div>
        </form>
        <div class="modal_bottom"></div>

    
    </div>

    <!--<div class="cart-collaterals">
        <div class="col2-set">
            <div class="col-1">
    <?php echo $this->getChildHtml('crosssell') ?>
            </div>
            <div class="col-2">
    <?php echo $this->getChildHtml('coupon') ?>
    <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping');
    endif; ?>
            </div>
        </div>
        <div class="totals">
    <?php echo $this->getChildHtml('totals'); ?>
    <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
        <?php echo $this->getChildHtml('methods') ?>
            </ul>
    <?php endif; ?>
        </div>
    </div>-->
</div>
</div>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/lightbox.js') ?>"></script>
<script type="text/javascript">
    var url1 = document.location.href;
    var test1;
    var url1 = url1.split("#");
    Event.observe(window, 'load', function () {
        test1 = new Lightbox('gift-form');
        if(url1[1]== "gift/") { test1.open(); }
    });

    Event.observe('lightboxLink', 'click', function () {
        test1.open();
    });

    Event.observe('closeLink', 'click', function () {
        test1.close();
    });

    Event.observe(window, 'load', function () {
        test2 = new Lightbox('gift-deleteform');

    });

    Event.observe('lightboxLinkDelete', 'click', function () {
        test2.open();
    });

    Event.observe('closeLinkDelete', 'click', function () {
        test2.close();
    });
</script>
<script type="text/javascript">
    //< ![CDATA[
    var myForm= new VarienForm('giftoption', true);
    //]]>
</script>