<?php $data = $this->getAddressesHtml('billing'); ?>
<style>
.page-title h2 {padding-left:50px;padding-top:5px;}
</style>
<form id="co-billing-form" action="">

    <p class="required floatright"><?php echo $this->__('* Required Fields') ?></p>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
	   <li class="fields">
       <input type="hidden" name='billing-address-select' id='billing-address-select' value="<?php echo $data['entity_id'] ?>" >
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getCustomer())->toHtml() ?>
       </li>
       <li class="field">
            <div class="field">
                <label for="billing:email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                <div class="input-box">
                    <input disabled="disabled" type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                </div>
            </div>
        </li>
        <li class="field">
            <label for="telephone" class="required"><?php echo $this->__('Telephone') ?><em>*</em></label>
            <div class="input-box" style="margin-bottom:0px;">
                <input type="text" name="telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="telephone" />
            </div>
        </li>
        <li class="field">
                   
                <div class="field " id="clselectremovepad">
                    <label for="region_id" class="required"><?php echo $this->__('State/Province') ?><em>*</em></label>
                    <div  class="floatleft input-box">
                        <?php echo $this->getRegionHtmlSelect();?>
                    </div>
                </div>
            </li>
           <li class="field" >
                <label for="street_1" class="required"><?php echo $this->__('Street Address') ?><em>*</em></label>
                <div  style="padding:10px 0 10px 0;float:left" class="clsstreet"  >
                    <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                </div>
            </li>
            <li class="field">
                    <label for="zip" class="required"><?php echo $this->__('Zip/Postal Code') ?><em>*</em></label>
                    <div class="input-box">
                        <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
                        <input type="hidden" value="<?php echo $data['entity_id'] ?>" name="" />
                    </div>
               
            </li>
            
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <fieldset>
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            <ul>
                <li class="field"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
                <?php if(!$this->isCustomerLoggedIn()): ?>
       			 	<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        			<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            		<?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                		<li class="fields">
                			<?php if ($_dob->isEnabled()): ?>
                    			<div class="field">
                        			<?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    			</div>
                			<?php endif; ?>
                			<?php if ($_gender->isEnabled()): ?>
                    			<div class="field">
                        			<?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    			</div>
                			<?php endif ?>
                		</li>
            		<?php endif ?>
              <?php endif ?>  
                
                <li class="field">
                     
        <?php if(!$this->isCustomerLoggedIn()): ?>
                    <div class="field">
                        <label for="billing:email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </div>
        <?php endif ?>
                </li>
               
       
                <li class="field">
                        <!--label for="billing:city" class="required"><?php echo $this->__('City') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="billing:city" />
                        </div-->
						<input type="hidden" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="billing:city" />
                    <div class="field clsinputbox">
                        <label for="billing:region_id" class="required"><?php echo $this->__('State/Province') ?><em>*</em></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select clsselctbox" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
								
                            //]]>
                            </script>
                            <!--input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" -->
                        </div>
                    </div>
                </li>
                 <li class="field">
                    <label for="billing:street1" class="required"><?php echo $this->__('Address') ?><em>*</em></label>
                    <div class="input-box" >
                        <input type="text"  title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" />
                    </div>
                </li>
                <li class="field">
                    <div class="field">
                        <label for="billing:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international required-entry" />
                        </div>
                    </div>
                   
                </li>
                <li lang="fields" class="field">
                        <label for="billing:telephone" class="required"><?php echo $this->__('Telephone') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="billing:telephone" />
                        </div>
                   
                </li>
                <?php if(!$this->isCustomerLoggedIn()): ?>
       			 	
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
                <li>
                    <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                </li>
        <?php endif ?>

                <li class="field" id="register-customer-password">
                        <label for="billing:customer_password" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    <div class="field">
                        <label for="billing:confirm_password" class="required"><?php echo $this->__('Confirm Password') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                <?php endif; ?>
                <div class="clear"></div>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control" style="margin:0 0 0 165px;">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book" style="float:none;display:inline;"><?php echo $this->__('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
            </ul>
        </fieldset>
     </li>
    <?php if ($this->canShip()): ?>
        <li class="control">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label></li>
        <li class="control">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo $this->__('Ship to different address') ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label>
        </li>
    <?php endif; ?>
    </ul>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>
    <div class="buttons-set" id="billing-buttons-container">

<!--        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="billing.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>-->
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="btnnew floatright" onclick="billing.save()"><span><?php echo $this->__('Continue') ?></span></button>
        <span class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>

<input type="hidden" name="billing[country_id]" id="billing:country_id" value="VN" />
	
</form>
<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
<?php if ($this->customerHasAddresses()){ ?>	

    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
	<?php } else {  ?>
	$('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
	<?php } ?>
		
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
	//var a = $('billing:region_id').value;
		jQuery(document).ready(function(){
			//
			jQuery('select[name=billing[region_id]]').change(function(){
				var country = jQuery('select[name=billing[region_id]] option:selected').text();
				jQuery('input[name=billing[city]]').val(country);
			});
			
	});
	
//]]>

</script>
