<style>
.col-main .contpad {padding-top:0px;}
</style>
<div class="page-title title-cart">
    <h2><?php echo $this->__('Checkout') ?></h2>
</div>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<div class="one-page-checkout" id="checkoutSteps"> 
	<div class="boxStep">
   
		<?php 
		
		$i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): 
		
		?>
        <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
   			<div class="step stepNone" id="act-<?php echo $_stepId ?>"><?php echo $_stepInfo['label'] ?></div>
		<?php endforeach ?>    
     </div>
     <?php $j=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
    	<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $j++; ?>
      <div id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
            <?php echo $this->getChildHtml($_stepId); ?>
        </div>
        </div>
     <?php endforeach ?>    
</div>

<script type="text/javascript">
//<![CDATA[
	/*
	jQuery(document).ready(function(){
		var actId = '<?php echo 'act-'.$this->getActiveStep() ?>';
		jQuery('#'+actId).removeClass('stepNone');
		jQuery('#'+actId).addClass('stepActive');
	});
	*/
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    	accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
	
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>

<!--
<ol class="one-page-checkout" id="checkoutSteps">
< ?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
< ?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
    <li id="opc-< ?php echo $_stepId ?>" class="section< ?php echo !empty($_stepInfo['allow'])?' allow':'' ?>< ?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div class="step-title">
            <span class="number">< ?php echo $i ?></span>
            <h3>< ?php echo $_stepInfo['label'] ?></h3>
        </div>
        <div id="checkout-step-< ?php echo $_stepId ?>" class="step a-item" style="display:none;">
            < ?php echo $this->getChildHtml($_stepId) ?>
        </div>
    </li>
< ?php endforeach ?>
</ol>-->
