<p><?php echo $this->getMethod()->getTitle() ?></p>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getMailingAddress()): ?>
        <p><strong><?php echo Mage::helper('payment')->__('Tài khoản thụ hưởng:') ?></strong></p>
        <address class="checkmo-mailing-address">
            <?php echo nl2br($this->htmlEscape($this->getMailingAddress())) ?>
        </address>
    <?php endif; ?>
<?php endif; ?>
