
<div class="account-create">
    <div class="page-title account-page " style="padding-left:23px;">
        <h1><?php echo $this->__('Create an Account') ?></h1>
       <?php echo $this->__('If you have an account with us, please log in'); ?> <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" style="text-decoration: none; color:#2671d0">Tại đây</a>
    </div>
    <!--<p class="back-link"><a href="<?php //echo $this->getBackUrl() ?>" class="back-link"><small>&laquo; </small><?php //echo $this->__('Back') ?></a></p>-->
 
<div id="account-page" style="">
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
    
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
         
            <ul class="form-list">               
                <li class="field">
                    <label for="email_address" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                    <div class="input-box" id="emailaddress">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="logintxtbox required-entry"/>
                    </div>
                </li>
				<li class="fields">
                    <div class="field">
                        <label for="password" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><?php echo $this->__('Confirm Password') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>                    
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>               
                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li class="field"><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li class="field"><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li class="field"><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
			<li class="control" id="showcity" style=" padding:10px 0 0 0;">
				<div class="field">
					<label  class="required" style="vertical-align:top;"><?php echo $this->__('City') ?><em>*</em></label>
					<select id="city" name="city" >
						 <?php echo   Mage::getSingleton('core/session')->getCitydropdown(); ?>
					</select>
				</div>
            </li>
            </ul>
			
    <?php if($this->getShowAddressFields()): ?>
    
            <input type="hidden" name="create_address" value="1" />        
            <ul class="form-list">				 
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                        </div>
                    </div>                   
                </li>
                <li class="wide">
                    <label for="street_1" class="required"><?php echo $this->__('Street Address') ?><em>*</em></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                    </div>
                </li>
            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address '.$_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                    </div>
                </li>
            <?php endfor ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><?php echo $this->__('City') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><?php echo $this->__('State/Province') ?><em>*</em></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><?php echo $this->__('Zip/Postal Code') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><?php echo $this->__('Country') ?><em>*</em></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect(); ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
      
    <?php endif; ?>

                   <div id="clsclear"></div>
	<div class="page-title account-page" style="padding-top:20px; margin-left:-45px;">
        <h1><?php echo $this->__('Thông tin giao hàng') ?></h1>        
    </div>
            <ul class="form-list">
               
            
				<!--hanhdt edit form register-->
				<li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml(); ?>
                </li>
				<li>
					 <div class="field">
                        <label for="telephone" class="required"><?php echo $this->__('Telephone') ?><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()); ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />
                        </div>
                    </div>
				</li>
				
				<li>
                <div class="field">
						<?php echo @$_SESSION['ctform']['captcha_error']; ?>
						<label for="code"  class="required"><?php echo Mage::helper('customer')->__('Enter the code'); ?> <em>*</em></label>
						 <div class="input-box">
						 
					<p>
						<img id="siimage" style="border: 1px solid #000; margin-right: 15px" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>/captcha/securimage_show.php?sid=<?php echo md5(uniqid()) ?>" alt="CAPTCHA Image" align="left">
   						<a tabindex="-1" style="border-style: none;" href="#" title="Refresh Image" onclick="document.getElementById('siimage').src = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>/captcha/securimage_show.php?sid=' + Math.random(); this.blur(); return false">
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>/captcha/images/refresh.png" alt="Reload Image" onclick="this.blur()" align="bottom" border="0"></a><br />
					</p><br>	
							<input type="text" name="ct_captcha"  maxlength="8" class="input-text required-entry validate-cpassword"/>
						</div>
					
                </div>
				</li>				
				 <!-- <?php if($this->getLayout()->createBlock('cms/block')->setBlockId('privacypolicy')->toHtml()){ ?>
                      <li class="fields">
                   <div class="field">
                      <label for="Privacy Policy" class="required"><?php echo $this->__('Privacy Policy') ?><em>*</em></label>
                      <div class="input-box">
                       <textarea rows="10" cols="5" name="privacypolicy" id="privacypolicy" title="<?php echo strip_tags($this->__('Privacy Policy')); ?>"  class="txtarea" readonly="true" style="resize: none;">
                              <?php echo strip_tags($this->getLayout()->createBlock('cms/block')->setBlockId('privacypolicy')->toHtml());?>
                       </textarea></div>
                   </div>
                   </li>
                  
                <?php }?>-->
				
				 <li class="control" style="padding-bottom:5px; padding-top:5px;">
						<div id="clsclear">                       
                        <input type="checkbox" name="privacypolicy" title="<?php echo $this->__('Privacy Policy') ?>" value="1" id="privacypolicy"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox required-entry" />
                        <span for="privacypolicy" style="vertical-align:top;"><?php echo $this->__('I accept') ?> <a href="<?php echo $this->getPrivacyPolicy(); ?>"><?php echo $this->__('Privacy Policy') ?></a></span></div>
					</li>
				<li class="control">
                    <div id="clsclear">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsdeal') ?>" value="1" onClick="showcity(this.checked)" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        <span for="is_subscribed" style="vertical-align:top;"><?php echo $this->__('Sign Up for Newsdeal') ?></span></div>
				</li>
                <li>
				 <div  class="account-toptxt clearfix">
				 <span class="requiredfield "><font style="color:red">* </font><?php echo $this->__('Required Fields') ?></span>
				</div>
<!--                    <div style="margin:10px 0 0 162px"><button type="submit" title="<?php echo $this->__('Submit') ?>" class="button accountsubmit"></button></div>-->
<div style="margin:10px 0 0 162px"><button type="submit" title="<?php echo $this->__('Submit') ?>" class="btnsubmit"><span><?php echo $this->__('Submit') ?></span></button></div>
                </li>
            </ul>
       
        
    </form></div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>

            function showcity(arg){
                if(arg==true)
                    {
                        document.getElementById('showcity').style.display="none";
                        document.getElementById('showcity').style.display="block";
                    }
                    else{
                        document.getElementById('showcity').style.display="none";
                    }
            }
    //]]>
    </script>
</div>
