<form id="form-validate" method="post" action="<?php echo $this->getUrl('advertsystem/index/invitesend') ?>">
    <div class="fieldset group-select">
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->__('Invite Friends Via Email'); ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                    <?php $addonClass = ""; ?>
                    <?php if (version_compare(Mage::getVersion(), "1.3.2.4", "<="))
                        $addonClass = " input-box"; ?>
                    <div class="field<?php echo $addonClass; ?> name-firstname">
                        <label class="required" style="color:#666666" for="email"><?php echo Mage::helper('advertsystem')->__('Name of your friend'); ?><em style="color:#EB340A">*</em></label>
                        <div class="input-box" style="padding-bottom:20px;">
                            <input class="input-text required-entry" title="Name" name="invite[name]" id="name" style="width:100%;"/>
                        </div>
                        <div class="clear"></div>
                        <label class="required" style="color:#666666" for="email"><?php echo Mage::helper('advertsystem')->__('Email Id of your friend'); ?><em style="color:#EB340A">*</em></label>
                        <div class="input-box" style="padding-bottom:20px;">
                            <input class="input-text validate-email required-entry" title="Email" name="invite[email]" id="email" style="width:100%;"/>
                        </div>
                        <div class="clear"></div>
                        <label class="required" style="color:#666666" for="email"><?php echo Mage::helper('advertsystem')->__('Subject'); ?><em style="color:#EB340A">*</em></label>
                        <div class="input-box" style="padding-bottom:20px;">
                            <input class="input-text required-entry" title="Subject" name="invite[subject]" id="subject" style="width:100%;"/>
                        </div>
                        <div class="clear"></div>
                        <label class="required" style="color:#666666" for="email"><?php echo Mage::helper('advertsystem')->__('Message'); ?><em style="color:#EB340A">*</em></label>
                        <div class="input-box">
                            <textarea class="input-text required-entry" title="Message" name="invite[message]" id="message" style="width:100%; height:200px"></textarea>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </li>

            <li>
                <div style="padding:20px 0 0 165px;">
                    <button class="btnnew form-button" title="<?php echo Mage::helper('advertsystem')->__("Invite"); ?>" type="submit"><span><span>  <?php echo Mage::helper('advertsystem')->__("Invite !"); ?>  </span></span></button>
                </div>
                <div> <p class="required"><?php echo Mage::helper('advertsystem')->__("* Required Fields"); ?></p></div>
            </li>
        </ul>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>