					<?php 
						$currentPage = (int) $this->getRequest()->getParam('p', 1);

						$pageSize = 2;
						//die($this->getRequest()->getParam('cat'));
						$cat_id = 11;//(int) $this->getRequest()->getParam('cat');
						$dealsCity = Mage::getSingleton('core/session')->getCity();;
						//$products = Mage::getModel('deal/deal')->getDealCollections($catId, $dealsCity);
						$data = $this->getTourByCity($cat_id, $dealsCity,$currentPage,$pageSize);
						$products	=	$data['products'];
						//$toolbar = Mage::getBlockSingleton('catalog/product_list')->getToolbarBlock();
						//$toolbar->setCollection($products);
						//echo $toolbar->toHtml();
						//echo count($_products);
						$i=0;
					?>
						
                        <?php foreach($products as $k => $_product):?>
                        <?php 
                        	$model = Mage::getModel('catalog/product');
                        	$_product = $model->load($_product->getId());
                        	//echo '<pre>';
                        	$URL = Mage::getModel('deal/deal')->getProductUrl($_product->getId());
                        	$quantity =(int) Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();
                        	//die($quantity.'aaaaaaaaaaaaaaaa'); 
                        	//print_r($_product->getData());die();
                        ?>
                    <?php 
                    //die($k.'asasas');
                    if($i==0):
                    //die('asasa');
                    ?>
                    <!--Fine Print and Highlights-->
                    <div style="margin:0px 5px 15px 8px; float: left; width:600px;">
            <?php
            	$count=1;
            	$_gallery = $_product->getMediaGalleryImages();
                        /* get video collection and display hdflvplayer. */
                        if ($videoId != '') {
                            $productVideo = Mage::getStoreConfig('videoupload/frontend/default');

                            if ($productVideo == 'video') {
                                $displayVideo = 'display:block;';
                                $displayImage = 'style="display:none"';
                            } else if ($productVideo == 'image') {
                                $displayVideo = 'display:none;';
                                $displayImage = 'style="display:block;width: 435px; height: 276px;"';
                            }
                        } else {
                            $displayVideo = 'display:none;';
                            $displayImage = 'style="display:block;width: 435px; height: 276px;"';
                        }
            ?>

                        <div id="featured-<?php echo $count; ?>" <?php echo $displayImage; ?> >
                            <div class="banner_middle"  id='image-<?php echo $count; ?>'>
                    			<?php if (count($_gallery) != 1) {
			                            foreach ($_gallery as $_image): ?>
								<?php $imageSrc = $this->helper('catalog/image')->init($this->getProduct(), 'baseimage', $_image->getFile()); ?>
								                                <img src="<?php echo $imageSrc ?>" width="670" height="310" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"  />
								<?php endforeach; ?>
								
								<?php } else { ?>
								                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" width="670" height="310" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"  />
								<?php } ?>
					        </div>
					    </div>
					<?php if (count($_gallery) != 1) { ?>
                                <script type="text/javascript">
                                    $j('#featured-<?php echo $count; ?>').orbit({
                                        'bullets': true,
                                        'bulletid': <?php echo $count; ?>,
                                        'timer' : true,
                                        'animation' : 'fade',
                                        'captions' : false,
                                        'directionalNav' : false
                                    });
                                </script>
					<?php } ?>
                            
                            <div class="bottom clearfix">
                                <div class="spread_detail clearfix">
                                   
		                    <?php
		                            // Prepare URL for the facebook dialog feed.
		                            $appId = Mage::getStoreConfig('customer/facebook/api_id');
		                            $productUrl = Mage::getModel('deal/deal')->getProductUrl($productId);;
		                            $redirectUrl = Mage::getBaseUrl();
		                            $productImage = $this->helper('catalog/image')->init($_product, 'image');
		                            $productName = urlencode($_product->getName());
		                            $productDescription = urlencode(strip_tags($_description));
		                            $fbUrl = 'http://www.facebook.com/dialog/feed?app_id=' . $appId . '&description=' . $productDescription . '&picture=' . $productImage . '&name=' . $productName . '&message=&redirect_uri=' . $redirectUrl . '&link=' . $productUrl;
		                    ?>
		                            <span class="" style="width:670px;">
		                            	<?php echo $this->htmlEscape($_product->getName()) ?>
		                        	</span>
		
		                    	</div>
		                    </div>
                    <!--end of Fine Print and Highlights-->
                    </div>
                    <?php else:?>
                    <div class="clsrecentbox" style="margin:0px 5px 15px 8px;">
                        <!--h2 class="floatright"><?php echo $this->__('%s', $this->formatDate($_product->getspecial_to_date(), 'long')) ?></h2-->
	                    <div class="clear"></div>
	                    <div class="clsbord">
	                        <form name="recentForm<?php echo $count;?>" method="post">
	                            <input type="hidden" value="1" name="recent"/>
	                        </form>
	                        
	                        <a href="<?php echo $URL;?>">
	                            <div>	
	                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(404, 276); ?>" width="325" height="213" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="border-radium1" />
	                                <div class="detail-recent border-bottom-radius1">
	                                	<div class="info-recent">
	                                        <span><?php echo substr($this->htmlEscape($_product->getName()), 0, 25) . "..." ?></span>
	                                        <span style="font-size:14px;font-weight:normal;color:#dbdbdb;">Phieu du lich</span>
	                                    </div>
	                                    <div class="info-price">
	                                        <span style="font-size:14px;color:#dbdbdb;text-decoration:line-through;"><?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?></span>	
	                                        <span style="font-size:16px;color:#ef5506;text-shadow:1px 1px 1px #FFFFFF;"><strong><?php echo Mage::helper('core')->currency($_product->getSpecialPrice(), true, false) ?></strong></span>
	                                    </div>
	                                </div>
	                            </div>
	                        </a>	
	                        
	                      
	        	        </div>
                	</div>
                	<?php endif;$i++;?>
                        <?php endforeach;?>
                        <?php echo $this->pagination('',$data['num_rows'],$pageSize,$currentPage);?>
                        <?php echo $this->getPagerHtml();?>