

<div  class="tabtwo">
    <div class="mailform"><h4><?php echo $this->__('Business Recommendations') ?></h4><div class="clsmailform">

            <?php  $status = $this->getBd();
if($status != 'success') {
    if($status == 'failed') {
        echo "<span style='color:red'>* Mail sending failed</span><br>";
                        }  ?>
            <form action="<?php echo Mage::helper('core/url')->getCurrentUrl() ; ?>" method="post" id="bd-detail">
                <fieldset class="block-content">
                    <legend><?php echo $this->__('Business Recommendations') ?></legend>
                        <?php /*
            <?php if( $message = $this->getErrorMessage() ): ?>
                <p class="error"><?php echo $message ?></p>
            <?php endif; ?>
            <?php if( $message = $this->getSuccessMessage() ): ?>
                <p class="success"><?php echo $message ?></p>
            <?php endif; ?>*/
    ?>
                    <div class="">
                        <label>Email Address: </label> <input name="emailbusiness" type="text" id="newsletter" class="txtmail" style="margin-top:5px;" onfocus="if (this.value == 'Enter Your Email address...') {this.value = '';this.style.color ='black';}" onblur="if (this.value == '') {this.style.color ='silver';this.value = 'Enter Your Email address...';}" value="Enter Your Email address..." />
                        <br><label>Enter your content here:</label> <br>    <textarea name="bdrecommend" cols="75" rows="10" style="margin-bottom: 8px" onfocus="if (this.value == 'Type your content here...') {this.value = '';this.style.color ='black';}" onblur="if (this.value == '') {this.style.color ='silver';this.value = 'Type your content here...';}" value="Type your content here..." >Type your content here...</textarea></div>
                    <button type="submit" class="clssubmit" name="bd"></button>
                </fieldset>
            </form> <?php }else {
    echo "Your mail has been sent";
} ?>






        </div>
    </div>
</div>