
<div class="MenuTop">
	<div class="left"></div>
    <div style="float:right;">
		<ul id="nav1">
			<li><a href="<?php echo Mage::getBaseUrl() . "customer/account/create/" ?>" >Đăng ký</a></li>
            <li style="background:none;"><a href="<?php echo Mage::getBaseUrl() . "customer/account/login/" ?>" >Đăng nhập</a></li>
        </ul>
    </div>
</div>

<!--ul id="nav1">
		<?php foreach ($this->getStoreCategories() as $_category): ?>
            <?php echo $this->drawItem($_category) ?>
        <?php endforeach ?>
        </ul-->